version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - hold:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy:
          type: approval
          requires:
            - hold
          filters:
            branches:
              only: master
jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: React Build
          command: npm run build
      - slack/status:
          mentions: 'U0151GNJQ22,U0156TZ3JGM'
      - persist_to_workspace:
          root: .
          paths:
              - .
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run: 
          name: React Test
          command: npm run test
      - slack/status:
          mentions: 'U0151GNJQ22,U0156TZ3JGM'
  hold:
    executor: node
    steps:
      - slack/approval:
          channel: C015LT4SQ2D
          color: '#ff8b33'
  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
      - slack/status:
          mentions: 'U0151GNJQ22,U0156TZ3JGM'     
orbs:
  slack: circleci/slack@3.4.2
